version: 0.1
fancybox: true
#duoshuo: iou2much
duoshuo: false
#disqus: ## Your disqus_shortname, e.g. haomwei
#google_search: ## Use Google search, true/false
#baidu_search: ## Use Baidu search, true/false
#swiftype: WwxGua3vYy9n-MTGjPSp
swiftype: false
#swiftype: false
#tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
#google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: 4492c5298a95d05e162aa9bd5f8b145b
#baidu_analytics: false
shareto: true ## If you want to use the share button please set the value to true.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.

menu:
  - page: home
    directory: /
    icon: icon-home
  - page: 技能树
    directory: mindmap/
    icon: icon-tree
  - page: Notebook
    directory: notebook/
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-book
#  - page: about
#    directory: about/
#    icon: icon-user
#  - page: rss
#    directory: subscribe/
#    icon: icon-rss
links:
  - title: Notebook
    url: http://notebook.debug.life/tree
  - title: Jupyter
    url: http://jupyter.debug.life/
  - title: Hexo大牛
    url: http://www.lancezhange.com/
  - title: site-name3
    url: http://www.example3.com/

#highlight:
#  enable: true
#  auto_detect: true
#  line_number: true
#  tab_replace:

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

# Static files
js: js
css: css
